#!/usr/bin/env python3
def factorize(n):
    for i in range(2, int(n ** 0.5) + 1):
        if n % i:
            continue
        return i, n // i
    return n, 1
def main():
    with open('factorss', 'r') as f:
        for line in f:
            n = int(line.strip())
            p, q = factorize(n)
            print(f'{n}={p}*{q}')
if __name__ == '__main__':
    main()
